name: Upload to Google Drive

on:
  push:
    branches:
      - main  # یا برنچی که می‌خوای trigger شود

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          chmod 600 ~/.config/rclone/rclone.conf
          rclone version

      - name: Test rclone connection
        run: rclone about gdrive: || (echo "❌ کانفیگ یا remote درست نیست" && exit 1)

      - name: Upload folder to Google Drive
        run: |
          rclone copy ./my-folder gdrive:/backup -P
